# # cayman@v0.2.0
# # midnight@v0.2.0
# # slate@v0.2.0
# # dinky@v0.2.0
# # leap-day@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

title: ANGULAR with BLAZOR WEB-COMPONENTS
description: This repository showcases the integration of a Blazor WebAssembly Library project used as a Web-Component in the Angular App
